# Generated by the QA Intelligence Platform for standalone CI execution.
from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ProjectConfig:
    project_id: int
    target_url: str = ""
    login_url: str = ""
    environment: str = ""


def get_project_config(project_id: int) -> ProjectConfig:
    env_url = os.environ.get("VTEST_APP_BASE_URL") or os.environ.get("APP_BASE_URL")
    if env_url:
        return ProjectConfig(project_id=project_id, target_url=env_url)

    for p in (
        Path(__file__).resolve().parent.parent / "manifest.json",
        Path("tests/automation/manifest.json"),
        Path("qa-automation/manifest.json"),
        Path("manifest.json"),
    ):
        if p.is_file():
            try:
                data = json.loads(p.read_text(encoding="utf-8"))
                url = data.get("base_url") or data.get("target_url")
                if url:
                    return ProjectConfig(
                        project_id=project_id,
                        target_url=url,
                        login_url=data.get("login_url", ""),
                        environment=data.get("environment", ""),
                    )
            except Exception:
                pass
    return ProjectConfig(project_id=project_id, target_url="")
