# Generated by the QA Intelligence Platform for standalone CI execution.
from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path


@dataclass(frozen=True)
class Credentials:
    username: str = ""
    password: str = field(default="", repr=False)
    role: str = ""
    label: str = ""


def get_credentials(project_id: int, credential_label: str = "login") -> Credentials:
    env_user = os.environ.get("VTEST_DATA_USERNAME") or os.environ.get("TEST_USERNAME")
    env_pass = os.environ.get("VTEST_DATA_PASSWORD") or os.environ.get("TEST_PASSWORD")
    if env_user:
        return Credentials(username=env_user, password=env_pass or "", label=credential_label)

    for p in (
        Path(__file__).resolve().parent.parent / "manifest.json",
        Path("tests/automation/manifest.json"),
        Path("qa-automation/manifest.json"),
        Path("manifest.json"),
    ):
        if p.is_file():
            try:
                data = json.loads(p.read_text(encoding="utf-8"))
                creds = data.get("credentials") or {}
                if creds:
                    return Credentials(
                        username=creds.get("username", ""),
                        password=creds.get("password", ""),
                        role=creds.get("role", ""),
                        label=credential_label,
                    )
            except Exception:
                pass
    return Credentials(username="", password="", label=credential_label)
