# Generated by the QA Intelligence Platform for standalone CI execution.
from __future__ import annotations

import os


def selected_environment() -> tuple[str, str]:
    return (
        str(os.environ.get("VTEST_ENVIRONMENT") or "").strip(),
        str(os.environ.get("VTEST_PROJECT_KEY") or "").strip(),
    )
