# Generated by the QA Intelligence Platform for standalone CI execution.
from __future__ import annotations

import json
import os
from collections.abc import Mapping
from typing import Any


class TestData(Mapping[str, Any]):
    __test__ = False

    def __init__(self) -> None:
        self._values: dict[str, Any] | None = None

    def _load(self) -> dict[str, Any]:
        if self._values is None:
            raw = os.environ.get("VTEST_TEST_DATA") or "{}"
            try:
                payload = json.loads(raw)
            except Exception:
                payload = {}
            values = payload.get("values") if isinstance(payload, dict) else payload
            self._values = dict(values) if isinstance(values, dict) else {}
        return self._values

    def __getitem__(self, key: str) -> Any:
        return self._load().get(key)

    def __iter__(self):
        return iter(self._load())

    def __len__(self) -> int:
        return len(self._load())

    def text(self, key: str) -> str:
        val = self._load().get(key)
        return "" if val is None else str(val)


_instance = None


def get_test_data() -> TestData:
    global _instance
    if _instance is None:
        _instance = TestData()
    return _instance
